config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, only: %i[create new index]

  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 100 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name password email])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def new
    @post = Post.new
  end

  def create
    user = User.find(current_user.id)
    @post = user.posts.build(post_params)
    if @post.save
      flash[:notice] = 'Post saved successfully.'
      redirect_to root_path
    else
      flash.now[:alert] = 'Error trying to save your post.'
      render 'new'
    end
  end

  def index
    @posts = Post.all.order('created_at DESC')
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>

<body>
    <%= render("shared/header") %>
    <% if notice %><p class="alert alert-success"><a class="close" data-dismiss="alert">&times;</a><%= notice %></p><% end %>
    <% if alert %><p class="alert alert-error"><a class="close" data-dismiss="alert">&times;</a><%= alert %></p><% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>

</html>

app/views/posts/index.html.erb
<div class="container pt-5">

    <%= link_to "New Post", new_post_path, class:"btn btn-primary" %>
    <% if @posts.length > 0 %>
    <table class="table">
        <thead>
            <tr>
                <%if current_user %>
                <th scope="col">Author</th>
                <%end %>
                <th scope="col">Title</th>
                <th scope="col">Content</th>
            </tr>
        </thead>
        <tbody>
            <% @posts.each do |post| %>
            <tr>
                <% if current_user%>
                <td><%= post.user.name %></td>
                <% end %>
                <td><%= post.title %></td>
                <td><%= post.content %></td>
            </tr>
            <%end %>
        </tbody>
    </table>
    <%else %>
    <h1>No post available here. You can create one <%= link_to "here", new_post_path %></h1>
    <%end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>


<%= form_with model: @post do |form| %>
<%= form.label :title, "Title: "%>
<%= form.text_field :title %>
<%= form.label :content, "Content: "%>
<%= form.text_field :content %>
<%= form.submit %>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <div class="container-fluid">
        <%= link_to "Members only" ,root_path, class: "navbar-brand text text-white" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <% if !current_user %>
                <li class="nav-item">
                    <%= link_to "Login", new_user_session_path, class:"nav-link active" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Signup", new_user_registration_path, class:"nav-link active" %>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= current_user.name %>
                </li>
                <li class="nav-item">
                    <%= link_to "Log out", destroy_user_session_path,method: :delete, class:"nav-link active" %>
                </li>
                <%end %>
            </ul>

        </div>
    </div>
</nav>